In [1]:
import pandas as pd

In [6]:
department=pd.read_csv("departments_pandas_task.csv")
d_df=pd.DataFrame(department)
d_df

  department_id  department  manager_name   location   budget
0           D01          IT   Rahul Menon      Kochi  5000000
1           D02          HR   Anjali Nair  Bangalore  3000000
2           D03     Finance    Arun Kumar    Chennai  4000000
3           D04   Marketing     Meera Das     Mumbai  3500000
4           D05       Sales    Vishnu Raj  Hyderabad  4500000
5           D06  Operations  Sneha Thomas       Pune  4200000

In [7]:
employees=pd.read_csv("employees_pandas_task.csv")
e_df=pd.DataFrame(employees)
e_df

,employee_id,first_name,department,job_role,gender,age,city,experience_years,salary,performance_score,attendance_percentage,projects_completed,work_mode,education,joining_year,manager_id,bonus,satisfaction_score
0,E1001,Akhil,Marketing,SEO Analyst,Male,43,Chennai,12,87492,65,96.7,4,Remote,BCom,2020,M102,28967,7
1,E1002,Arjun,Operations,Process Analyst,Female,49,Hyderabad,5,60976,79,82.3,11,Remote,MCA,2018,M107,3267,4
2,E1003,Reshma,Finance,Accountant,Female,34,Bangalore,4,60086,63,75.4,2,Remote,BSc,2022,M108,14206,6
3,E1004,Sneha,Operations,Process Analyst,Female,26,Pune,0,32585,96,89.2,13,Remote,MCA,2025,M102,6297,9
4,E1005,Sneha,Marketing,SEO Analyst,Male,48,Kochi,13,84629,94,96.1,13,Hybrid,MSc,2023,M110,23243,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,E1309,Devika,HR,HR Executive,Female,21,Trivandrum,4,57434,76,80.7,15,Office,BTech,2024,M110,8837,5
501,E1014,Arjun,Finance,Finance Executive,Female,28,Kochi,3,54382,65,83.5,9,Hybrid,BCom,2025,M103,18646,7
502,E1415,Diya,Operations,Operations Manager,Female,37,Chennai,7,76147,56,99.3,4,Office,MSc,2023,M109,18195,5
503,E1033,Fathima,Operations,Operations Executive,Male,23,Hyderabad,14,83386,79,88.8,5,Office,BTech,2022,M105,23545,5
504,E1461,Akhil,IT,Data Analyst,Female,29,Chennai,10,78957,100,82.6,9,Office,MBA,2016,M107,25369,5

In [9]:
d_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  6 non-null      object
 1   department     6 non-null      object
 2   manager_name   6 non-null      object
 3   location       6 non-null      object
 4   budget         6 non-null      int64
dtypes: int64(1), object(4)
memory usage: 372.0+ bytes

In [10]:
e_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            505 non-null    object
 1   first_name             505 non-null    object
 2   department             505 non-null    object
 3   job_role               505 non-null    object
 4   gender                 505 non-null    object
 5   age                    505 non-null    int64
 6   city                   505 non-null    object
 7   experience_years       505 non-null    int64
 8   salary                 505 non-null    int64
 9   performance_score      505 non-null    int64
 10  attendance_percentage  505 non-null    float64
 11  projects_completed     505 non-null    int64
 12  work_mode              505 non-null    object
 13  education              505 non-null    object
 14  joining_year           505 non-null    int64
 15  manager_id             505 non-null    object
 16  bonus                  505 non-null    int64
 17  satisfaction_score     505 non-null    int64
dtypes: float64(1), int64(8), object(9)
memory usage: 71.1+ KB

In [ ]:
# Level 1 – Filtering & Selection
# 1. Display the employees whose salary is greater than 60,000.
# 2. Find all employees who have more than 5 years of experience.
# 3. Display employees working in the IT department with a performance score greater than 8.
# 4. Find employees whose attendance percentage is below 85.
# 5. Display employees who have completed more than 10 projects.
# 6. Find employees working in either Kochi or Bangalore.
# 7. Display employees whose satisfaction score is 8 or above and whose experience is at least 5 years.
# 8. Find employees whose salary is between 40,000 and 70,000.

In [22]:
# 1. Display the employees whose salary is greater than 60,000.
e_df[e_df["salary"]>60000][["first_name","salary"]]

    first_name  salary
0        Akhil   87492
1        Arjun   60976
2       Reshma   60086
4        Sneha   84629
5        Akhil   90608
..         ...     ...
498      Akhil   65049
499     Aparna  101537
502       Diya   76147
503    Fathima   83386
504      Akhil   78957

[313 rows x 2 columns]

In [23]:
# 2. Find all employees who have more than 5 years of experience.
e_df[e_df["experience_years"]>5][["first_name","experience_years"]]

    first_name  experience_years
0        Akhil                12
4        Sneha                13
5        Akhil                12
6        Sneha                 6
8        Rohan                13
..         ...               ...
498      Akhil                 9
499     Aparna                14
502       Diya                 7
503    Fathima                14
504      Akhil                10

[312 rows x 2 columns]

In [25]:
# 3. Display employees working in the IT department with a performance score greater than 8.
e_df[(e_df["department"]=="IT") & (e_df["satisfaction_score"]>8)]

,employee_id,first_name,department,job_role,gender,age,city,experience_years,salary,performance_score,attendance_percentage,projects_completed,work_mode,education,joining_year,manager_id,bonus,satisfaction_score
21,E1022,Nikhil,IT,Tester,Male,28,Pune,7,73491,70,76.3,3,Remote,BSc,2017,M102,24303,10
39,E1040,Fathima,IT,Developer,Male,34,Chennai,0,42779,60,98.7,5,Remote,BTech,2017,M110,21255,9
84,E1085,Amal,IT,Data Analyst,Female,43,Chennai,15,98617,96,99.8,11,Remote,MSc,2017,M103,9206,9
116,E1117,Rohan,IT,Data Analyst,Male,32,Pune,6,69114,74,78.1,14,Office,BSc,2017,M110,19275,10
118,E1119,Aparna,IT,Tester,Male,21,Chennai,11,88401,85,91.5,5,Office,BTech,2025,M102,7105,9
119,E1120,Nikhil,IT,Developer,Male,33,Trivandrum,0,52975,95,77.7,2,Office,BCom,2019,M106,6114,9
130,E1131,Anjali,IT,Tester,Male,32,Chennai,6,65946,86,88.5,6,Hybrid,MBA,2021,M110,9426,9
133,E1134,Neha,IT,Data Analyst,Female,28,Trivandrum,13,87819,86,78.2,12,Hybrid,BSc,2017,M104,22960,10
171,E1172,Sneha,IT,Data Analyst,Female,48,Hyderabad,14,104823,60,94.8,7,Remote,MSc,2018,M102,3898,9
216,E1217,Anjali,IT,Tester,Male,29,Pune,12,110495,65,93.3,6,Office,BSc,2022,M102,22360,10
241,E1242,Devika,IT,Tester,Male,23,Kochi,12,99797,66,91.8,13,Remote,BTech,2016,M103,11689,10
256,E1257,Anjali,IT,Developer,Female,31,Chennai,5,68595,92,85.7,4,Hybrid,BSc,2020,M102,26417,10
307,E1308,Rohan,IT,Tester,Female,32,Trivandrum,7,72427,80,94.7,8,Remote,MSc,2021,M110,20888,10
318,E1319,Sanjay,IT,Developer,Male,25,Trivandrum,8,87513,77,85.4,12,Hybrid,MSc,2023,M109,3609,9
320,E1321,Amal,IT,Developer,Female,38,Pune,15,107886,65,85.5,3,Hybrid,MBA,2020,M110,8799,9
321,E1322,Fathima,IT,Data Analyst,Female,48,Mumbai,11,81320,58,99.3,2,Hybrid,MBA,2023,M107,20286,10
430,E1431,Varun,IT,Tester,Female,32,Bangalore,13,105610,85,97.2,1,Remote,MCA,2020,M108,29885,10
432,E1433,Nikhil,IT,Data Analyst,Male,43,Hyderabad,7,78658,98,77.2,5,Remote,BCom,2018,M105,7616,10
440,E1441,Amal,IT,Data Analyst,Male,32,Bangalore,6,70790,96,82.7,12,Remote,MCA,2017,M110,24990,9
494,E1495,Rohan,IT,Developer,Female,34,Mumbai,4,67238,74,89.6,5,Remote,MSc,2017,M107,16781,9

In [26]:
# 4. Find employees whose attendance percentage is below 85.
e_df[e_df["attendance_percentage"]<85]

,employee_id,first_name,department,job_role,gender,age,city,experience_years,salary,performance_score,attendance_percentage,projects_completed,work_mode,education,joining_year,manager_id,bonus,satisfaction_score
1,E1002,Arjun,Operations,Process Analyst,Female,49,Hyderabad,5,60976,79,82.3,11,Remote,MCA,2018,M107,3267,4
2,E1003,Reshma,Finance,Accountant,Female,34,Bangalore,4,60086,63,75.4,2,Remote,BSc,2022,M108,14206,6
5,E1006,Akhil,Marketing,Marketing Executive,Female,21,Hyderabad,12,90608,62,75.1,11,Remote,BTech,2023,M103,14666,8
7,E1008,Aparna,IT,ML Engineer,Male,29,Trivandrum,2,48472,69,77.8,12,Office,MBA,2022,M101,10755,8
13,E1014,Arjun,Finance,Finance Executive,Female,28,Kochi,3,54382,65,83.5,9,Hybrid,BCom,2025,M103,18646,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,E1489,Rahul,IT,ML Engineer,Male,22,Trivandrum,4,56252,87,81.8,14,Office,MBA,2022,M109,6071,4
498,E1499,Akhil,Sales,Business Development Executive,Male,46,Trivandrum,9,65049,78,79.7,13,Hybrid,BTech,2023,M104,29391,5
500,E1309,Devika,HR,HR Executive,Female,21,Trivandrum,4,57434,76,80.7,15,Office,BTech,2024,M110,8837,5
501,E1014,Arjun,Finance,Finance Executive,Female,28,Kochi,3,54382,65,83.5,9,Hybrid,BCom,2025,M103,18646,7
504,E1461,Akhil,IT,Data Analyst,Female,29,Chennai,10,78957,100,82.6,9,Office,MBA,2016,M107,25369,5

In [27]:
# 5. Display employees who have completed more than 10 projects.
e_df[e_df["projects_completed"]>10]

,employee_id,first_name,department,job_role,gender,age,city,experience_years,salary,performance_score,attendance_percentage,projects_completed,work_mode,education,joining_year,manager_id,bonus,satisfaction_score
1,E1002,Arjun,Operations,Process Analyst,Female,49,Hyderabad,5,60976,79,82.3,11,Remote,MCA,2018,M107,3267,4
3,E1004,Sneha,Operations,Process Analyst,Female,26,Pune,0,32585,96,89.2,13,Remote,MCA,2025,M102,6297,9
4,E1005,Sneha,Marketing,SEO Analyst,Male,48,Kochi,13,84629,94,96.1,13,Hybrid,MSc,2023,M110,23243,7
5,E1006,Akhil,Marketing,Marketing Executive,Female,21,Hyderabad,12,90608,62,75.1,11,Remote,BTech,2023,M103,14666,8
7,E1008,Aparna,IT,ML Engineer,Male,29,Trivandrum,2,48472,69,77.8,12,Office,MBA,2022,M101,10755,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,E1488,Amal,HR,HR Executive,Male,47,Bangalore,10,57041,57,95.6,12,Hybrid,BCom,2021,M107,21613,8
488,E1489,Rahul,IT,ML Engineer,Male,22,Trivandrum,4,56252,87,81.8,14,Office,MBA,2022,M109,6071,4
496,E1497,Varun,HR,HR Analyst,Female,23,Bangalore,12,82773,70,88.8,12,Remote,BTech,2020,M102,10106,7
498,E1499,Akhil,Sales,Business Development Executive,Male,46,Trivandrum,9,65049,78,79.7,13,Hybrid,BTech,2023,M104,29391,5
500,E1309,Devika,HR,HR Executive,Female,21,Trivandrum,4,57434,76,80.7,15,Office,BTech,2024,M110,8837,5

In [28]:
# 6. Find employees working in either Kochi or Bangalore.
e_df[(e_df["city"]=="Kochi") | (e_df["city"]=="Banglore")][["first_name","city"]]

    first_name   city
4        Sneha  Kochi
9        Rohan  Kochi
13       Arjun  Kochi
16       Rahul  Kochi
19       Arjun  Kochi
..         ...    ...
474    Adithya  Kochi
480     Nikhil  Kochi
490     Nikhil  Kochi
499     Aparna  Kochi
501      Arjun  Kochi

[64 rows x 2 columns]