In [29]:
import pandas as pd
data=pd.read_csv("weather_classification_data.csv")
df=pd.DataFrame(data)
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Temperature           13200 non-null  float64
 1   Humidity              13200 non-null  int64
 2   Wind Speed            13200 non-null  float64
 3   Precipitation (%)     13200 non-null  float64
 4   Cloud Cover           13200 non-null  object
 5   Atmospheric Pressure  13200 non-null  float64
 6   UV Index              13200 non-null  int64
 7   Season                13200 non-null  object
 8   Visibility (km)       13200 non-null  float64
 9   Location              13200 non-null  object
 10  Weather Type          13200 non-null  object
dtypes: float64(5), int64(2), object(4)
memory usage: 1.1+ MB

In [31]:
X=df.drop("Weather Type",axis=1)
y=df["Weather Type"]
X

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain
...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain

In [32]:
X.dtypes

Temperature             float64
Humidity                  int64
Wind Speed              float64
Precipitation (%)       float64
Cloud Cover              object
Atmospheric Pressure    float64
UV Index                  int64
Season                   object
Visibility (km)         float64
Location                 object
dtype: object

In [33]:
X=pd.get_dummies(X)
X

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km),Cloud Cover_clear,Cloud Cover_cloudy,Cloud Cover_overcast,Cloud Cover_partly cloudy,Season_Autumn,Season_Spring,Season_Summer,Season_Winter,Location_coastal,Location_inland,Location_mountain
0,14.0,73,9.5,82.0,1010.82,2,3.5,False,False,False,True,False,False,False,True,False,True,False
1,39.0,96,8.5,71.0,1011.43,7,10.0,False,False,False,True,False,True,False,False,False,True,False
2,30.0,64,7.0,16.0,1018.72,5,5.5,True,False,False,False,False,True,False,False,False,False,True
3,38.0,83,1.5,82.0,1026.25,7,1.0,True,False,False,False,False,True,False,False,True,False,False
4,27.0,74,17.0,66.0,990.67,1,2.5,False,False,True,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,1003.15,1,1.0,False,False,True,False,False,False,True,False,False,False,True
13196,-1.0,76,3.5,23.0,1067.23,1,6.0,False,True,False,False,False,False,False,True,True,False,False
13197,30.0,77,5.5,28.0,1012.69,3,9.0,False,False,True,False,True,False,False,False,True,False,False
13198,3.0,76,10.0,94.0,984.27,0,2.0,False,False,True,False,False,False,False,True,False,True,False
13199,-5.0,38,0.0,92.0,1015.37,5,10.0,False,False,True,False,True,False,False,False,False,False,True

In [34]:
# Encoding target column using label encoding(Nave bayes)
# =======================================================
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)
# print(le.classes_)
y

array([1, 0, 3, ..., 0, 2, 1], shape=(13200,))

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [36]:
# KNN>>Scaling is required
# Naive Bayes sclaing is usually not required

In [37]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred

array([3, 3, 0, ..., 2, 0, 0], shape=(3960,))

In [38]:
le.inverse_transform(y_pred)

array(['Sunny', 'Sunny', 'Cloudy', ..., 'Snowy', 'Cloudy', 'Cloudy'],
      shape=(3960,), dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

# accuracy score calculation---->number of correct predictions/total no. of elements in y_test
# returns the accuracy score

0.7906565656565656