In [58]:
import pandas as pd

In [59]:
customer=pd.read_csv("customer5_windows.csv")
df=pd.DataFrame(customer)

In [60]:
# 1. Display the first 10 rows of the DataFrame.
df.head(10)

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,india,45000
1,4000002,Paige,Chen,74,Teacher,uk,45987
2,4000003,Sherri,Melton,34,Firefighter,us,78956
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
4,4000005,Karen,Puckett,74,Lawyer,africa,45680
5,4000006,Patrick,Song,42,Veterinarian,australia,500000
6,4000007,Elsie,Hamilton,43,Pilot,ireland,369000
7,4000008,Hazel,Bender,63,Carpenter,india,400000
8,4000009,Malcolm,Wagner,39,Artist,india,789560
9,4000010,Dolores,McLaughlin,60,Writer,india,45000

In [61]:
# 2. Display the last 10 rows of the DataFrame.
df.tail(10)

,id,fname,lname,age,prof,loc,salary
63,4000064,Calvin,Diaz,65,Athlete,us,960000
64,4000065,Eugene,Graham,52,Police officer,us,75205
65,4000066,Vickie,Watkins,55,Computer support specialist,us,1700000
66,4000067,Luis,Hinton,69,Childcare worker,us,456985
67,4000068,Allan,Marsh,67,Athlete,us,478962
68,4000069,Melanie,Hewitt,47,Real estate agent,us,456987
69,4000070,Marianne,Branch,53,Judge,us,258974
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
71,4000072,Caroline,O'Brien,44,Computer support specialist,us,478921
72,4000073,Arlene,Case,62,Musician,us,159879

In [62]:
# 3. Display 10 random rows from the DataFrame using sample().
df.sample(10)

,id,fname,lname,age,prof,loc,salary
46,4000047,Christina,Bowden,47,Computer software engineer,uk,85000
65,4000066,Vickie,Watkins,55,Computer support specialist,us,1700000
47,4000048,Darlene,Barton,54,Doctor,uk,75000
27,4000028,Dwight,Monroe,45,Economist,uk,45000
30,4000031,Neal,Middleton,59,Civil engineer,uk,35000
53,4000054,Judith,Cooper,22,Economist,uk,1500000
38,4000039,Erica,Hall,33,Police officer,uk,25000
43,4000044,Patricia,Mangum,67,Civil engineer,uk,450000
7,4000008,Hazel,Bender,63,Carpenter,india,400000
69,4000070,Marianne,Branch,53,Judge,us,258974

In [63]:
# 4. Display the number of rows and columns in the DataFrame.
df.shape

(73, 7)

In [64]:
# 5. Display all the column names of the DataFrame.
df.columns

Index(['id', 'fname', 'lname', 'age', 'prof', 'loc', 'salary'], dtype='object')

In [65]:
# 6. Display the data types of all columns.
df.dtypes

id         int64
fname     object
lname     object
age        int64
prof      object
loc       object
salary     int64
dtype: object

In [66]:
# 7. Display complete information about the DataFrame using info().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      73 non-null     int64
 1   fname   73 non-null     object
 2   lname   73 non-null     object
 3   age     73 non-null     int64
 4   prof    73 non-null     object
 5   loc     73 non-null     object
 6   salary  73 non-null     int64
dtypes: int64(3), object(4)
memory usage: 4.1+ KB

In [67]:
# 8. Generate statistical information for the numerical columns using describe().
df.describe()

                 id        age        salary
count  7.300000e+01  73.000000  7.300000e+01
mean   4.000037e+06  48.410959  5.760101e+05
std    2.121713e+01  14.817253  1.567045e+06
min    4.000001e+06  21.000000  3.685000e+03
25%    4.000019e+06  39.000000  5.000000e+04
50%    4.000037e+06  47.000000  8.000000e+04
75%    4.000055e+06  63.000000  4.500000e+05
max    4.000073e+06  74.000000  1.000000e+07

In [68]:
# 9. Find the number of unique professions available in the prof column.
df["prof"].nunique

<bound method IndexOpsMixin.nunique of 0                             Pilot
1                           Teacher
2                       Firefighter
3        Computer hardware engineer
4                            Lawyer
                  ...
68                Real estate agent
69                            Judge
70    Recreation and fitness worker
71      Computer support specialist
72                         Musician
Name: prof, Length: 73, dtype: object>

In [69]:
# 10. Display all the different values available in the loc column
df["loc"].unique()

array(['india', 'uk', 'us', 'china', 'africa', 'australia', 'ireland'],
      dtype=object)

In [70]:
# Part B – Selecting Columns and Filtering
# 11. Display only the fname, lname, and salary columns.
# 12. Display employees whose salary is greater than 100000.
# 13. Display employees whose age is greater than 50.
# 14. Display employees who are working as Pilots.
# 15. Display employees whose location is India.
# 16. Display employees whose salary is between 50000 and 100000.
# 17. Display employees whose age is below 30 and salary is greater than 50000.
# 18. Display employees who are either from India or UK.
# 19. Display employees who are Computer professionals and have a salary greater than 50000.
# 20. Display employees whose profession is not Pilot.

In [71]:
# 11. Display only the fname, lname, and salary columns.
df[["fname","lname","salary"]]

       fname    lname   salary
0   Kristina    Chung    45000
1      Paige     Chen    45987
2     Sherri   Melton    78956
3   Gretchen     Hill    98570
4      Karen  Puckett    45680
..       ...      ...      ...
68   Melanie   Hewitt   456987
69  Marianne   Branch   258974
70   Natalie   Walton  7896254
71  Caroline  O'Brien   478921
72    Arlene     Case   159879

[73 rows x 3 columns]

In [72]:
# 12. Display employees whose salary is greater than 100000.
df[df["salary"]>100000]

,id,fname,lname,age,prof,loc,salary
5,4000006,Patrick,Song,42,Veterinarian,australia,500000
6,4000007,Elsie,Hamilton,43,Pilot,ireland,369000
7,4000008,Hazel,Bender,63,Carpenter,india,400000
8,4000009,Malcolm,Wagner,39,Artist,india,789560
11,4000012,Sandy,Raynor,26,Writer,india,450000
28,4000029,Wayne,Connolly,40,Real estate agent,uk,250000
32,4000033,Tim,Watts,58,Lawyer,uk,500000
39,4000040,Douglas,Ross,27,Secretary,uk,450000
43,4000044,Patricia,Mangum,67,Civil engineer,uk,450000
50,4000051,Frederick,Baker,52,Writer,uk,250000
52,4000053,Jason,Cross,56,Civil engineer,uk,200000
53,4000054,Judith,Cooper,22,Economist,uk,1500000
54,4000055,Gretchen,Holmes,39,Childcare worker,uk,1700000
55,4000056,Don,Sharpe,53,Social worker,uk,2250000
56,4000057,Glenda,Morgan,37,Real estate agent,uk,160000
57,4000058,Scott,Hoyle,40,Doctor,uk,500000
58,4000059,Pat,Allen,45,Secretary,uk,10000000
59,4000060,Michelle,Rich,44,Artist,uk,4500000
60,4000061,Jessica,Rich,37,Actor,uk,650000
61,4000062,Evan,Grant,66,Agricultural and food scientist,uk,470000
62,4000063,Melinda,Proctor,27,Teacher,uk,410000
63,4000064,Calvin,Diaz,65,Athlete,us,960000
65,4000066,Vickie,Watkins,55,Computer support specialist,us,1700000
66,4000067,Luis,Hinton,69,Childcare worker,us,456985
67,4000068,Allan,Marsh,67,Athlete,us,478962
68,4000069,Melanie,Hewitt,47,Real estate agent,us,456987
69,4000070,Marianne,Branch,53,Judge,us,258974
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
71,4000072,Caroline,O'Brien,44,Computer support specialist,us,478921
72,4000073,Arlene,Case,62,Musician,us,159879

In [73]:
# 13. Display employees whose age is greater than 50.
df[df["age"]>50]

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,india,45000
1,4000002,Paige,Chen,74,Teacher,uk,45987
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
4,4000005,Karen,Puckett,74,Lawyer,africa,45680
7,4000008,Hazel,Bender,63,Carpenter,india,400000
9,4000010,Dolores,McLaughlin,60,Writer,india,45000
13,4000014,Beth,Woodard,65,Musician,india,75000
15,4000016,Jerome,Wallace,52,Pharmacist,india,36000
16,4000017,Neal,Lawrence,72,Computer support specialist,india,95000
18,4000019,Kristine,Dougherty,63,Financial analyst,india,25000
19,4000020,Crystal,Powers,67,Engineering technician,india,55555
21,4000022,Eric,Steele,66,Doctor,india,3685
26,4000027,Marcia,Walsh,64,Accountant,india,95000
30,4000031,Neal,Middleton,59,Civil engineer,uk,35000
32,4000033,Tim,Watts,58,Lawyer,uk,500000
37,4000038,Beth,Walton,73,Firefighter,uk,50000
40,4000041,Donald,Chung,65,Computer hardware engineer,uk,50000
42,4000043,Paul,Woods,63,Doctor,uk,50000
43,4000044,Patricia,Mangum,67,Civil engineer,uk,450000
47,4000048,Darlene,Barton,54,Doctor,uk,75000
48,4000049,Harvey,Underwood,70,Engineering technician,uk,25000
49,4000050,William,Jones,53,Photographer,uk,80000
50,4000051,Frederick,Baker,52,Writer,uk,250000
52,4000053,Jason,Cross,56,Civil engineer,uk,200000
55,4000056,Don,Sharpe,53,Social worker,uk,2250000
61,4000062,Evan,Grant,66,Agricultural and food scientist,uk,470000
63,4000064,Calvin,Diaz,65,Athlete,us,960000
64,4000065,Eugene,Graham,52,Police officer,us,75205
65,4000066,Vickie,Watkins,55,Computer support specialist,us,1700000
66,4000067,Luis,Hinton,69,Childcare worker,us,456985
67,4000068,Allan,Marsh,67,Athlete,us,478962
69,4000070,Marianne,Branch,53,Judge,us,258974
72,4000073,Arlene,Case,62,Musician,us,159879

In [74]:
# 14. Display employees who are working as Pilots.
df[df["prof"]=="Pilot"]

        id     fname     lname  age   prof      loc  salary
0  4000001  Kristina     Chung   55  Pilot    india   45000
6  4000007     Elsie  Hamilton   43  Pilot  ireland  369000

In [75]:
# 15. Display employees whose location is India.
df[df["loc"]=="india"]

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,india,45000
7,4000008,Hazel,Bender,63,Carpenter,india,400000
8,4000009,Malcolm,Wagner,39,Artist,india,789560
9,4000010,Dolores,McLaughlin,60,Writer,india,45000
10,4000011,Francis,McNamara,47,Therapist,india,85000
11,4000012,Sandy,Raynor,26,Writer,india,450000
12,4000013,Marion,Moon,41,Carpenter,india,25000
13,4000014,Beth,Woodard,65,Musician,india,75000
14,4000015,Julia,Desai,49,Musician,india,26000
15,4000016,Jerome,Wallace,52,Pharmacist,india,36000
16,4000017,Neal,Lawrence,72,Computer support specialist,india,95000
17,4000018,Jean,Griffin,45,Childcare worker,india,65000
18,4000019,Kristine,Dougherty,63,Financial analyst,india,25000
19,4000020,Crystal,Powers,67,Engineering technician,india,55555
20,4000021,Alex,May,39,Environmental scientist,india,58789
21,4000022,Eric,Steele,66,Doctor,india,3685
22,4000023,Wesley,Teague,42,Carpenter,india,58789
23,4000024,Franklin,Vick,28,Dancer,india,50000
24,4000025,Claire,Gallagher,42,Musician,india,75000
25,4000026,Marian,Solomon,27,Lawyer,india,45000
26,4000027,Marcia,Walsh,64,Accountant,india,95000

In [76]:
# 16. Display employees whose salary is between 50000 and 100000.
df[(df["salary"]>50000)&(df["salary"]<100000)]

,id,fname,lname,age,prof,loc,salary
2,4000003,Sherri,Melton,34,Firefighter,us,78956
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
10,4000011,Francis,McNamara,47,Therapist,india,85000
13,4000014,Beth,Woodard,65,Musician,india,75000
16,4000017,Neal,Lawrence,72,Computer support specialist,india,95000
17,4000018,Jean,Griffin,45,Childcare worker,india,65000
19,4000020,Crystal,Powers,67,Engineering technician,india,55555
20,4000021,Alex,May,39,Environmental scientist,india,58789
22,4000023,Wesley,Teague,42,Carpenter,india,58789
24,4000025,Claire,Gallagher,42,Musician,india,75000
26,4000027,Marcia,Walsh,64,Accountant,india,95000
31,4000032,Gretchen,Goldstein,24,Engineering technician,uk,75000
33,4000034,Jerome,Johnston,38,Childcare worker,uk,80000
34,4000035,Shelley,Weeks,25,Reporter,uk,75000
35,4000036,Priscilla,Wilkerson,35,Agricultural and food scientist,uk,65000
44,4000045,Lois,Joseph,44,Musician,uk,80000
45,4000046,Louis,Rosenthal,31,Economist,uk,90000
46,4000047,Christina,Bowden,47,Computer software engineer,uk,85000
47,4000048,Darlene,Barton,54,Doctor,uk,75000
49,4000050,William,Jones,53,Photographer,uk,80000
64,4000065,Eugene,Graham,52,Police officer,us,75205

In [77]:
# 17. Display employees whose age is below 30 and salary is greater than 50000.
df[(df["age"]<30)&(df["salary"]>50000)]

,id,fname,lname,age,prof,loc,salary
11,4000012,Sandy,Raynor,26,Writer,india,450000
31,4000032,Gretchen,Goldstein,24,Engineering technician,uk,75000
34,4000035,Shelley,Weeks,25,Reporter,uk,75000
39,4000040,Douglas,Ross,27,Secretary,uk,450000
53,4000054,Judith,Cooper,22,Economist,uk,1500000
62,4000063,Melinda,Proctor,27,Teacher,uk,410000
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254

In [78]:
# 18. Display employees who are either from India or UK.
df[(df["loc"]=="india")|(df["loc"]=="uk")]

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,india,45000
1,4000002,Paige,Chen,74,Teacher,uk,45987
7,4000008,Hazel,Bender,63,Carpenter,india,400000
8,4000009,Malcolm,Wagner,39,Artist,india,789560
9,4000010,Dolores,McLaughlin,60,Writer,india,45000
10,4000011,Francis,McNamara,47,Therapist,india,85000
11,4000012,Sandy,Raynor,26,Writer,india,450000
12,4000013,Marion,Moon,41,Carpenter,india,25000
13,4000014,Beth,Woodard,65,Musician,india,75000
14,4000015,Julia,Desai,49,Musician,india,26000
15,4000016,Jerome,Wallace,52,Pharmacist,india,36000
16,4000017,Neal,Lawrence,72,Computer support specialist,india,95000
17,4000018,Jean,Griffin,45,Childcare worker,india,65000
18,4000019,Kristine,Dougherty,63,Financial analyst,india,25000
19,4000020,Crystal,Powers,67,Engineering technician,india,55555
20,4000021,Alex,May,39,Environmental scientist,india,58789
21,4000022,Eric,Steele,66,Doctor,india,3685
22,4000023,Wesley,Teague,42,Carpenter,india,58789
23,4000024,Franklin,Vick,28,Dancer,india,50000
24,4000025,Claire,Gallagher,42,Musician,india,75000
25,4000026,Marian,Solomon,27,Lawyer,india,45000
26,4000027,Marcia,Walsh,64,Accountant,india,95000
27,4000028,Dwight,Monroe,45,Economist,uk,45000
28,4000029,Wayne,Connolly,40,Real estate agent,uk,250000
29,4000030,Stephanie,Hawkins,50,Human resources assistant,uk,45000
30,4000031,Neal,Middleton,59,Civil engineer,uk,35000
31,4000032,Gretchen,Goldstein,24,Engineering technician,uk,75000
32,4000033,Tim,Watts,58,Lawyer,uk,500000
33,4000034,Jerome,Johnston,38,Childcare worker,uk,80000
34,4000035,Shelley,Weeks,25,Reporter,uk,75000
35,4000036,Priscilla,Wilkerson,35,Agricultural and food scientist,uk,65000
36,4000037,Elsie,Barton,27,Childcare worker,uk,50000
37,4000038,Beth,Walton,73,Firefighter,uk,50000
38,4000039,Erica,Hall,33,Police officer,uk,25000
39,4000040,Douglas,Ross,27,Secretary,uk,450000
40,4000041,Donald,Chung,65,Computer hardware engineer,uk,50000
41,4000042,Katherine,Bender,44,Physicist,uk,25000
42,4000043,Paul,Woods,63,Doctor,uk,50000
43,4000044,Patricia,Mangum,67,Civil engineer,uk,450000
44,4000045,Lois,Joseph,44,Musician,uk,80000
45,4000046,Louis,Rosenthal,31,Economist,uk,90000
46,4000047,Christina,Bowden,47,Computer software engineer,uk,85000
47,4000048,Darlene,Barton,54,Doctor,uk,75000
48,4000049,Harvey,Underwood,70,Engineering technician,uk,25000
49,4000050,William,Jones,53,Photographer,uk,80000
50,4000051,Frederick,Baker,52,Writer,uk,250000
51,4000052,Shirley,Merritt,21,Reporter,uk,40000
52,4000053,Jason,Cross,56,Civil engineer,uk,200000
53,4000054,Judith,Cooper,22,Economist,uk,1500000
54,4000055,Gretchen,Holmes,39,Childcare worker,uk,1700000
55,4000056,Don,Sharpe,53,Social worker,uk,2250000
56,4000057,Glenda,Morgan,37,Real estate agent,uk,160000
57,4000058,Scott,Hoyle,40,Doctor,uk,500000
58,4000059,Pat,Allen,45,Secretary,uk,10000000
59,4000060,Michelle,Rich,44,Artist,uk,4500000
60,4000061,Jessica,Rich,37,Actor,uk,650000
61,4000062,Evan,Grant,66,Agricultural and food scientist,uk,470000
62,4000063,Melinda,Proctor,27,Teacher,uk,410000

In [79]:
# 19. Display employees who are Computer professionals and have a salary greater than 50000.
df[(df["prof"].str.contains("Computer"))&(df["salary"]>50000)]

,id,fname,lname,age,prof,loc,salary
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
16,4000017,Neal,Lawrence,72,Computer support specialist,india,95000
46,4000047,Christina,Bowden,47,Computer software engineer,uk,85000
65,4000066,Vickie,Watkins,55,Computer support specialist,us,1700000
71,4000072,Caroline,O'Brien,44,Computer support specialist,us,478921

In [80]:
# 20. Display employees whose profession is not Pilot.
df[df["prof"]!="Pilot"]

,id,fname,lname,age,prof,loc,salary
1,4000002,Paige,Chen,74,Teacher,uk,45987
2,4000003,Sherri,Melton,34,Firefighter,us,78956
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
4,4000005,Karen,Puckett,74,Lawyer,africa,45680
5,4000006,Patrick,Song,42,Veterinarian,australia,500000
...,...,...,...,...,...,...,...
68,4000069,Melanie,Hewitt,47,Real estate agent,us,456987
69,4000070,Marianne,Branch,53,Judge,us,258974
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
71,4000072,Caroline,O'Brien,44,Computer support specialist,us,478921
72,4000073,Arlene,Case,62,Musician,us,159879

In [81]:
# Part C – loc and iloc
# 21. Using iloc, display the first 10 rows and first 5 columns.
# 22. Using iloc, display rows from index position 20 to 30.
# 23. Using iloc, display only the fname, prof, and salary columns by their column positions.
# 24. Using loc, display the fname, lname, and salary of employees whose salary is greater than 100000.
# 25. Using loc, display employees whose loc is India and whose age is greater than 40.
# 26. Using loc, increase the salary of employees whose current salary is below 30000 by 5000.
# 27. Using loc, change the location of employees whose profession is Pilot from india to India.

In [82]:
# 21. Using iloc, display the first 10 rows and first 5 columns.
df.iloc[0:10,0:5]

        id     fname       lname  age                        prof
0  4000001  Kristina       Chung   55                       Pilot
1  4000002     Paige        Chen   74                     Teacher
2  4000003    Sherri      Melton   34                 Firefighter
3  4000004  Gretchen        Hill   66  Computer hardware engineer
4  4000005     Karen     Puckett   74                      Lawyer
5  4000006   Patrick        Song   42                Veterinarian
6  4000007     Elsie    Hamilton   43                       Pilot
7  4000008     Hazel      Bender   63                   Carpenter
8  4000009   Malcolm      Wagner   39                      Artist
9  4000010   Dolores  McLaughlin   60                      Writer

In [83]:
# 22. Using iloc, display rows from index position 20 to 30.
df.iloc[20:31,:]

,id,fname,lname,age,prof,loc,salary
20,4000021,Alex,May,39,Environmental scientist,india,58789
21,4000022,Eric,Steele,66,Doctor,india,3685
22,4000023,Wesley,Teague,42,Carpenter,india,58789
23,4000024,Franklin,Vick,28,Dancer,india,50000
24,4000025,Claire,Gallagher,42,Musician,india,75000
25,4000026,Marian,Solomon,27,Lawyer,india,45000
26,4000027,Marcia,Walsh,64,Accountant,india,95000
27,4000028,Dwight,Monroe,45,Economist,uk,45000
28,4000029,Wayne,Connolly,40,Real estate agent,uk,250000
29,4000030,Stephanie,Hawkins,50,Human resources assistant,uk,45000
30,4000031,Neal,Middleton,59,Civil engineer,uk,35000

In [84]:
# 23. Using iloc, display only the fname, prof, and salary columns by their column positions.
df.iloc[:,[1,4,6]]

       fname                           prof   salary
0   Kristina                          Pilot    45000
1      Paige                        Teacher    45987
2     Sherri                    Firefighter    78956
3   Gretchen     Computer hardware engineer    98570
4      Karen                         Lawyer    45680
..       ...                            ...      ...
68   Melanie              Real estate agent   456987
69  Marianne                          Judge   258974
70   Natalie  Recreation and fitness worker  7896254
71  Caroline    Computer support specialist   478921
72    Arlene                       Musician   159879

[73 rows x 3 columns]

In [85]:
# 24. Using loc, display the fname, lname, and salary of employees whose salary is greater than 100000.
df.loc[df["salary"]>100000,["fname","lname","salary"]]

        fname     lname    salary
5     Patrick      Song    500000
6       Elsie  Hamilton    369000
7       Hazel    Bender    400000
8     Malcolm    Wagner    789560
11      Sandy    Raynor    450000
28      Wayne  Connolly    250000
32        Tim     Watts    500000
39    Douglas      Ross    450000
43   Patricia    Mangum    450000
50  Frederick     Baker    250000
52      Jason     Cross    200000
53     Judith    Cooper   1500000
54   Gretchen    Holmes   1700000
55        Don    Sharpe   2250000
56     Glenda    Morgan    160000
57      Scott     Hoyle    500000
58        Pat     Allen  10000000
59   Michelle      Rich   4500000
60    Jessica      Rich    650000
61       Evan     Grant    470000
62    Melinda   Proctor    410000
63     Calvin      Diaz    960000
65     Vickie   Watkins   1700000
66       Luis    Hinton    456985
67      Allan     Marsh    478962
68    Melanie    Hewitt    456987
69   Marianne    Branch    258974
70    Natalie    Walton   7896254
71   Caroline   O'Brien    478921
72     Arlene      Case    159879

In [86]:
# 26. Using loc, increase the salary of employees whose current salary is below 30000 by 5000.
df.loc[df["salary"]<30000,"salary"]+=5000
df

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,india,45000
1,4000002,Paige,Chen,74,Teacher,uk,45987
2,4000003,Sherri,Melton,34,Firefighter,us,78956
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
4,4000005,Karen,Puckett,74,Lawyer,africa,45680
...,...,...,...,...,...,...,...
68,4000069,Melanie,Hewitt,47,Real estate agent,us,456987
69,4000070,Marianne,Branch,53,Judge,us,258974
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
71,4000072,Caroline,O'Brien,44,Computer support specialist,us,478921
72,4000073,Arlene,Case,62,Musician,us,159879

In [ ]:
# 27. Using loc, change the location of employees whose profession is Pilot from india to India.

df.loc[(df["prof"]=="Pilot")&(df["loc"]=="india"),"loc"]="India"

    prof      loc
0  Pilot    India
6  Pilot  ireland

In [ ]:
# Part D – Sorting and DataFrame Methods
# 28. Sort the DataFrame based on salary in ascending order.
# 29. Sort the DataFrame based on salary in descending order and display the top 10 employees.
# 30. Sort the DataFrame first by loc and then by salary in descending order.
# 31. Find the average salary of all employees.
# 32. Find the highest salary and lowest salary.
# 33. Find the average age of all employees.
# 34. Count how many employees are available in each location using value_counts().

In [94]:
# 28. Sort the DataFrame based on salary in ascending order.

df.sort_values("salary")

,id,fname,lname,age,prof,loc,salary
21,4000022,Eric,Steele,66,Doctor,india,8685
18,4000019,Kristine,Dougherty,63,Financial analyst,india,30000
48,4000049,Harvey,Underwood,70,Engineering technician,uk,30000
41,4000042,Katherine,Bender,44,Physicist,uk,30000
38,4000039,Erica,Hall,33,Police officer,uk,30000
...,...,...,...,...,...,...,...
54,4000055,Gretchen,Holmes,39,Childcare worker,uk,1700000
55,4000056,Don,Sharpe,53,Social worker,uk,2250000
59,4000060,Michelle,Rich,44,Artist,uk,4500000
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
58,4000059,Pat,Allen,45,Secretary,uk,10000000

In [95]:
# 29. Sort the DataFrame based on salary in descending order and display the top 10 employees.
df.sort_values("salary",ascending=False).head(10)

,id,fname,lname,age,prof,loc,salary
58,4000059,Pat,Allen,45,Secretary,uk,10000000
70,4000071,Natalie,Walton,24,Recreation and fitness worker,us,7896254
59,4000060,Michelle,Rich,44,Artist,uk,4500000
55,4000056,Don,Sharpe,53,Social worker,uk,2250000
65,4000066,Vickie,Watkins,55,Computer support specialist,us,1700000
54,4000055,Gretchen,Holmes,39,Childcare worker,uk,1700000
53,4000054,Judith,Cooper,22,Economist,uk,1500000
63,4000064,Calvin,Diaz,65,Athlete,us,960000
8,4000009,Malcolm,Wagner,39,Artist,india,789560
60,4000061,Jessica,Rich,37,Actor,uk,650000

In [98]:
# 30. Sort the DataFrame first by loc and then by salary in descending order.
df.sort_values(["loc","salary"],ascending=[True,False])

,id,fname,lname,age,prof,loc,salary
0,4000001,Kristina,Chung,55,Pilot,India,45000
4,4000005,Karen,Puckett,74,Lawyer,africa,45680
5,4000006,Patrick,Song,42,Veterinarian,australia,500000
3,4000004,Gretchen,Hill,66,Computer hardware engineer,china,98570
8,4000009,Malcolm,Wagner,39,Artist,india,789560
...,...,...,...,...,...,...,...
66,4000067,Luis,Hinton,69,Childcare worker,us,456985
69,4000070,Marianne,Branch,53,Judge,us,258974
72,4000073,Arlene,Case,62,Musician,us,159879
2,4000003,Sherri,Melton,34,Firefighter,us,78956
64,4000065,Eugene,Graham,52,Police officer,us,75205

In [99]:
# 31. Find the average salary of all employees.
df["salary"].mean()

np.float64(576489.5616438356)

In [101]:
# 32. Find the highest salary and lowest salary.
df["salary"].max(),df["salary"].min()

(np.int64(10000000), np.int64(8685))

In [102]:
# 33. Find the average age of all employees.
df["age"].mean()

np.float64(48.41095890410959)

In [104]:
# 34. Count how many employees are available in each location using value_counts().
df["loc"].value_counts()

loc
uk           37
india        20
us           11
India         1
china         1
africa        1
australia     1
ireland       1
Name: count, dtype: int64

In [ ]:
# Part E – GroupBy and Aggregation
# 35. Find the average salary for each profession using groupby().
# 36. Find the maximum salary for each location using groupby().
# 37. Find the minimum salary for each profession using groupby().
# 38. Find the number of employees in each profession using groupby().
# 39. Find the average salary of employees in each location and sort the result from highest to lowest.
# 40. Find the average salary and average age for each profession using groupby() and agg().

In [105]:
# 35. Find the average salary for each profession using groupby().
df.groupby("prof")["salary"].mean()

prof
Accountant                         9.500000e+04
Actor                              6.500000e+05
Agricultural and food scientist    2.675000e+05
Artist                             2.644780e+06
Athlete                            7.194810e+05
Carpenter                          1.629297e+05
Childcare worker                   4.703970e+05
Civil engineer                     2.283333e+05
Computer hardware engineer         7.428500e+04
Computer software engineer         8.500000e+04
Computer support specialist        7.579737e+05
Dancer                             5.000000e+04
Doctor                             1.584212e+05
Economist                          5.450000e+05
Engineering technician             5.351833e+04
Environmental scientist            5.878900e+04
Financial analyst                  3.000000e+04
Firefighter                        6.447800e+04
Human resources assistant          4.500000e+04
Judge                              2.589740e+05
Lawyer                             1.968933e+05
Musician                           8.417580e+04
Pharmacist                         3.600000e+04
Photographer                       8.000000e+04
Physicist                          3.000000e+04
Pilot                              2.070000e+05
Police officer                     5.260250e+04
Real estate agent                  2.889957e+05
Recreation and fitness worker      7.896254e+06
Reporter                           5.750000e+04
Secretary                          5.225000e+06
Social worker                      2.250000e+06
Teacher                            2.279935e+05
Therapist                          8.500000e+04
Veterinarian                       5.000000e+05
Writer                             2.483333e+05
Name: salary, dtype: float64

In [106]:
# 36. Find the maximum salary for each location using groupby().
df.groupby("loc")["salary"].max()

loc
India           45000
africa          45680
australia      500000
china           98570
india          789560
ireland        369000
uk           10000000
us            7896254
Name: salary, dtype: int64

In [107]:
# 37. Find the minimum salary for each profession using groupby().
df.groupby("prof")["salary"].min()

prof
Accountant                           95000
Actor                               650000
Agricultural and food scientist      65000
Artist                              789560
Athlete                             478962
Carpenter                            30000
Childcare worker                     50000
Civil engineer                       35000
Computer hardware engineer           50000
Computer software engineer           85000
Computer support specialist          95000
Dancer                               50000
Doctor                                8685
Economist                            45000
Engineering technician               30000
Environmental scientist              58789
Financial analyst                    30000
Firefighter                          50000
Human resources assistant            45000
Judge                               258974
Lawyer                               45000
Musician                             31000
Pharmacist                           36000
Photographer                         80000
Physicist                            30000
Pilot                                45000
Police officer                       30000
Real estate agent                   160000
Recreation and fitness worker      7896254
Reporter                             40000
Secretary                           450000
Social worker                      2250000
Teacher                              45987
Therapist                            85000
Veterinarian                        500000
Writer                               45000
Name: salary, dtype: int64

In [108]:
# 38. Find the number of employees in each profession using groupby().
df.groupby("prof")["id"].count()

prof
Accountant                         1
Actor                              1
Agricultural and food scientist    2
Artist                             2
Athlete                            2
Carpenter                          3
Childcare worker                   5
Civil engineer                     3
Computer hardware engineer         2
Computer software engineer         1
Computer support specialist        3
Dancer                             1
Doctor                             4
Economist                          3
Engineering technician             3
Environmental scientist            1
Financial analyst                  1
Firefighter                        2
Human resources assistant          1
Judge                              1
Lawyer                             3
Musician                           5
Pharmacist                         1
Photographer                       1
Physicist                          1
Pilot                              2
Police officer                     2
Real estate agent                  3
Recreation and fitness worker      1
Reporter                           2
Secretary                          2
Social worker                      1
Teacher                            2
Therapist                          1
Veterinarian                       1
Writer                             3
Name: id, dtype: int64

In [110]:
# 39. Find the average salary of employees in each location and sort the result from highest to lowest.
df.groupby("loc")["salary"].mean().sort_values(ascending=False)

loc
us           1.181920e+06
uk           6.877294e+05
australia    5.000000e+05
ireland      3.690000e+05
india        1.289189e+05
china        9.857000e+04
africa       4.568000e+04
India        4.500000e+04
Name: salary, dtype: float64

In [112]:
# 40. Find the average salary and average age for each profession using groupby() and agg().
df.groupby("prof")[["salary","age"]].agg("mean")

                                       salary        age
prof
Accountant                       9.500000e+04  64.000000
Actor                            6.500000e+05  37.000000
Agricultural and food scientist  2.675000e+05  50.500000
Artist                           2.644780e+06  41.500000
Athlete                          7.194810e+05  66.000000
Carpenter                        1.629297e+05  48.666667
Childcare worker                 4.703970e+05  43.600000
Civil engineer                   2.283333e+05  60.666667
Computer hardware engineer       7.428500e+04  65.500000
Computer software engineer       8.500000e+04  47.000000
Computer support specialist      7.579737e+05  57.000000
Dancer                           5.000000e+04  28.000000
Doctor                           1.584212e+05  55.750000
Economist                        5.450000e+05  32.666667
Engineering technician           5.351833e+04  53.666667
Environmental scientist          5.878900e+04  39.000000
Financial analyst                3.000000e+04  63.000000
Firefighter                      6.447800e+04  53.500000
Human resources assistant        4.500000e+04  50.000000
Judge                            2.589740e+05  53.000000
Lawyer                           1.968933e+05  53.000000
Musician                         8.417580e+04  52.400000
Pharmacist                       3.600000e+04  52.000000
Photographer                     8.000000e+04  53.000000
Physicist                        3.000000e+04  44.000000
Pilot                            2.070000e+05  49.000000
Police officer                   5.260250e+04  42.500000
Real estate agent                2.889957e+05  41.333333
Recreation and fitness worker    7.896254e+06  24.000000
Reporter                         5.750000e+04  23.000000
Secretary                        5.225000e+06  36.000000
Social worker                    2.250000e+06  53.000000
Teacher                          2.279935e+05  50.500000
Therapist                        8.500000e+04  47.000000
Veterinarian                     5.000000e+05  42.000000
Writer                           2.483333e+05  46.000000