In [69]:
import pandas as pd
import numpy as np
customers=pd.read_csv("customers_dataset.csv")
orders=pd.read_csv("orders_dataset.csv")
df2=pd.DataFrame(orders)

In [9]:
df2

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000

In [ ]:
# 1. Load orders_dataset.csv into a DataFrame and display the first 5 rows.
df2.head(5)

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000

In [13]:
# 2. Display the last 5 rows and the shape of the DataFrame.
df2.tail(5)
df2.shape

(15, 9)

In [14]:
# 3. Display column names, data types, and basic information about the dataset.
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      15 non-null     int64
 1   CustomerID   15 non-null     int64
 2   Product      15 non-null     object
 3   Category     15 non-null     object
 4   Quantity     15 non-null     int64
 5   UnitPrice    15 non-null     int64
 6   City         15 non-null     object
 7   Status       15 non-null     object
 8   TotalAmount  15 non-null     int64
dtypes: int64(5), object(4)
memory usage: 1.2+ KB

In [15]:
# 4. Find the number of unique products and unique cities.
df2[["Product","City"]].nunique()

Product    15
City        6
dtype: int64

In [21]:
# 5. Display all orders where Category is Electronics.
df2[df2["Category"]=="Electronics"]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000

In [22]:
# 6. Display orders where Quantity is greater than 2.
df2[df2["Quantity"]>2]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300

In [23]:
# 7. Find the number of orders for each Status using value_counts().
df2["Status"].value_counts()

Status
Completed    10
Pending       3
Cancelled     2
Name: count, dtype: int64

In [ ]:
# 8. Calculate the total revenue of every order using Quantity and UnitPrice.
revenue=df2["Quantity"]*df2["UnitPrice"]
revenue

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000

In [32]:
# 9. Find the total revenue generated from all orders.
revenue.sum()

np.int64(213400)

In [33]:
# 10. Find the average UnitPrice for each Category using groupby().
df2.groupby("Category")["UnitPrice"].mean()

Category
Electronics    12444.444444
Furniture      11100.000000
Name: UnitPrice, dtype: float64

In [38]:
# 11. Find the total Quantity sold for each Product Category.
df2.groupby("Category")["Quantity"].sum()

Category
Electronics    20
Furniture       7
Name: Quantity, dtype: int64

In [41]:
df2

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000

In [43]:
# 12. Find the total revenue generated from each City.
df2.groupby("City").sum("TotalAmount")

            OrderID  CustomerID  Quantity  UnitPrice  TotalAmount
City
Kochi          4027         827         7      88500        95300
Kollam         2017         417         5      15600        32300
Kottayam       2024         424         2      37500        37500
Kozhikode      2011         411         2      15500        15500
Thrissur       3024         624         8       7900        17600
Trivandrum     2017         417         3      13600        15200

In [44]:
# 13. Find the average order value for each Status.
df2.groupby("Status")["TotalAmount"].mean()

Status
Cancelled    20000.000000
Completed    15470.000000
Pending       6233.333333
Name: TotalAmount, dtype: float64

In [ ]:
# 14. Find the maximum TotalAmount for each Category.
df2.groupby("Category")["TotalAmount"].max()

Category
Electronics    65000
Furniture      28000
Name: TotalAmount, dtype: int64

In [48]:
# 15. Sort the DataFrame by TotalAmount from highest to lowest.
df2.sort_values("TotalAmount",ascending=False)

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200

In [49]:
# 16. Display the top 5 highest-value orders.
df2.sort_values("TotalAmount",ascending=False).head(5)

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000

In [50]:
# 17. Find the product with the highest TotalAmount.
df2.sort_values("TotalAmount",ascending=False).head(1)

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000

In [52]:
# 18. Count how many orders were placed in each City and Status combination using groupby().
df2.groupby(["Status","City"]).count()

                      OrderID  CustomerID  Product  Category  Quantity  \
Status    City
Cancelled Kottayam          1           1        1         1         1
          Trivandrum        1           1        1         1         1
Completed Kochi             4           4        4         4         4
          Kollam            2           2        2         2         2
          Kottayam          1           1        1         1         1
          Thrissur          3           3        3         3         3
Pending   Kozhikode         2           2        2         2         2
          Trivandrum        1           1        1         1         1

                      UnitPrice  TotalAmount
Status    City
Cancelled Kottayam            1            1
          Trivandrum          1            1
Completed Kochi               4            4
          Kollam              2            2
          Kottayam            1            1
          Thrissur            3            3
Pending   Kozhikode           2            2
          Trivandrum          1            1

In [ ]:
# 19. Find the total revenue from Completed orders only.
df2[df2["Status"] == "Completed"]["TotalAmount"].sum()

In [61]:
# 20. Find cities whose total revenue is greater than 20000 using groupby() and a condition.
revenue = df2.groupby("City")["TotalAmount"].sum()
revenue[revenue > 20000]

City
Kochi       95300
Kollam      32300
Kottayam    37500
Name: TotalAmount, dtype: int64

In [63]:
# 21. Create a new column PriceLevel: 'High' if UnitPrice >= 10000, otherwise 'Normal'.
df2["PriceLevel"]=np.where(df2["UnitPrice"]>=10000,"High","Normal")
df2

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount,PriceLevel
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,High
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,Normal
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,Normal
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,Normal
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,High
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,High
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,Normal
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,Normal
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,Normal
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,Normal
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,Normal
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,Normal
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,High
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,High
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,Normal

In [64]:
# 22. Create a new column OrderValueLevel: 'Large' if TotalAmount >= 15000, otherwise 'Regular'.
df2["OrderValueLevel"]=np.where(df2["TotalAmount"]>=15000,"Large","Regular")
df2

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City,Status,TotalAmount,PriceLevel,OrderValueLevel
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,High,Large
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,Normal,Regular
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,Normal,Regular
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,Normal,Regular
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,High,Regular
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,High,Large
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,Normal,Regular
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,Normal,Regular
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,Normal,Regular
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,Normal,Regular
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,Normal,Regular
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,Normal,Regular
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,High,Large
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,High,Large
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,Normal,Regular

In [65]:
# 23. Find the average Quantity for Electronics and Furniture separately.
df2.groupby("Category")["Quantity"].mean()

Category
Electronics    2.222222
Furniture      1.166667
Name: Quantity, dtype: float64

In [67]:
# 24. Find the category with the highest total revenue.
df2.groupby("Category")["TotalAmount"].sum().sort_values(ascending=False).head(1)

Category
Electronics    145200
Name: TotalAmount, dtype: int64

In [68]:
# 25. Use groupby() with multiple aggregations to calculate total quantity, average unit price, and total revenue for
# each Category.
df2.groupby("Category").agg({
    "Quantity": "sum",
    "UnitPrice": "mean",
    "TotalAmount": "sum"
})

             Quantity     UnitPrice  TotalAmount
Category
Electronics        20  12444.444444       145200
Furniture           7  11100.000000        68200

In [70]:
# 26. Load customers_dataset.csv into a second DataFrame.
df1=pd.DataFrame(customers)

In [71]:
# 27. Perform an inner join between orders and customers using CustomerID.
result=pd.merge(df2,df1,on="CustomerID",how="inner")
result

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,Akhil,24,Male,Gold,Kochi
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,Anjali,27,Female,Silver,Thrissur
2,1003,203,Office Chair,Furniture,1,8500,Kozhikode,Pending,8500,Rahul,31,Male,Bronze,Kozhikode
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,Meera,29,Female,Gold,Kochi
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,Vishnu,35,Male,Silver,Trivandrum
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,Sneha,26,Female,Gold,Kollam
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,Arjun,23,Male,Bronze,Thrissur
7,1008,208,Bookshelf,Furniture,1,7000,Kozhikode,Pending,7000,Devika,32,Female,Silver,Kozhikode
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,Nikhil,28,Male,Gold,Kochi
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,Athira,30,Female,Gold,Kottayam
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,Sreehari,25,Male,Silver,Kollam
11,1012,212,Table Lamp,Furniture,2,1600,Trivandrum,Pending,3200,Fathima,34,Female,Bronze,Trivandrum
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,Joel,29,Male,Gold,Kochi
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,Gokul,36,Male,Silver,Kottayam
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,Keerthana,27,Female,Gold,Thrissur

In [74]:
# 28. Select and display CustomerName, Product, Quantity, TotalAmount, Membership, and City after the join.
result[["CustomerName","Product","Quantity","TotalAmount","Membership","City_x"]]

   CustomerName       Product  Quantity  TotalAmount Membership      City_x
0         Akhil        Laptop         1        65000       Gold       Kochi
1        Anjali    Headphones         2         5000     Silver    Thrissur
2         Rahul  Office Chair         1         8500     Bronze   Kozhikode
3         Meera      Keyboard         3         5400       Gold       Kochi
4        Vishnu          Desk         1        12000     Silver  Trivandrum
5         Sneha       Monitor         2        29000       Gold      Kollam
6         Arjun         Mouse         4         3600     Bronze    Thrissur
7        Devika     Bookshelf         1         7000     Silver   Kozhikode
8        Nikhil        Webcam         2         6400       Gold       Kochi
9        Athira   Study Table         1         9500       Gold    Kottayam
10     Sreehari       USB Hub         3         3300     Silver      Kollam
11      Fathima    Table Lamp         2         3200     Bronze  Trivandrum
12         Joel       Printer         1        18500       Gold       Kochi
13        Gokul          Sofa         1        28000     Silver    Kottayam
14    Keerthana    Microphone         2         9000       Gold    Thrissur

In [75]:
# 29. Find the total revenue generated by each customer.
result.groupby(["CustomerID", "CustomerName"])["TotalAmount"].sum()

CustomerID  CustomerName
201         Akhil           65000
202         Anjali           5000
203         Rahul            8500
204         Meera            5400
205         Vishnu          12000
206         Sneha           29000
207         Arjun            3600
208         Devika           7000
209         Nikhil           6400
210         Athira           9500
211         Sreehari         3300
212         Fathima          3200
213         Joel            18500
214         Gokul           28000
215         Keerthana        9000
Name: TotalAmount, dtype: int64

In [77]:
# 30. Find the total revenue generated by each Membership type.
result.groupby(["Membership"])["TotalAmount"].sum()

Membership
Bronze     15300
Gold      142800
Silver     55300
Name: TotalAmount, dtype: int64

In [78]:
# 31. Find the average order value for each Membership type.
result.groupby(["Membership"])["TotalAmount"].mean()

Membership
Bronze     5100.0
Gold      20400.0
Silver    11060.0
Name: TotalAmount, dtype: float64

In [82]:
# 32. Find the total quantity purchased by customers from each City.
result.groupby("City_x")["Quantity"].sum()

City_x
Kochi         7
Kollam        5
Kottayam      2
Kozhikode     2
Thrissur      8
Trivandrum    3
Name: Quantity, dtype: int64

In [84]:
# 33. Find the number of orders made by each Gender.
result.groupby("Gender")["OrderID"].count()

Gender
Female    7
Male      8
Name: OrderID, dtype: int64

In [85]:
# 34. Find the average customer age for each Membership type.
result.groupby("Membership")["Age"].mean()

Membership
Bronze    29.333333
Gold      27.571429
Silver    31.000000
Name: Age, dtype: float64

In [86]:
# 35. Find the customer who generated the highest total revenue.
result.groupby("CustomerName")["TotalAmount"].sum().sort_values(ascending=False).head(1)

CustomerName
Akhil    65000
Name: TotalAmount, dtype: int64

PART C

In [87]:
# 36. After joining the datasets, display only Gold members who placed Completed orders.
result[(result["Membership"]=="Gold") & (result["Status"]=="Completed")]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,Akhil,24,Male,Gold,Kochi
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,Meera,29,Female,Gold,Kochi
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,Sneha,26,Female,Gold,Kollam
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,Nikhil,28,Male,Gold,Kochi
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,Athira,30,Female,Gold,Kottayam
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,Joel,29,Male,Gold,Kochi
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,Keerthana,27,Female,Gold,Thrissur

In [88]:
# 37. Find Gold members whose TotalAmount is greater than 10000.
result[(result["Membership"]=="Gold") & (result["TotalAmount"]>10000)]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,Akhil,24,Male,Gold,Kochi
5,1006,206,Monitor,Electronics,2,14500,Kollam,Completed,29000,Sneha,26,Female,Gold,Kollam
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,Joel,29,Male,Gold,Kochi

In [89]:
# 38. Find customers older than 30 who placed Completed orders.
result[(result["Age"]>30)&(result["Status"]=="Completed")]

Empty DataFrame
Columns: [OrderID, CustomerID, Product, Category, Quantity, UnitPrice, City_x, Status, TotalAmount, CustomerName, Age, Gender, Membership, City_y]
Index: []

In [90]:
# 39. Find Female customers from Kochi and display their order details.
result[(result["Gender"]=="Female")&(result["City_x"]=="Kochi")]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
3,1004,204,Keyboard,Electronics,3,1800,Kochi,Completed,5400,Meera,29,Female,Gold,Kochi

In [91]:
# 40. Find Male customers who purchased Electronics products.
result[(result["Gender"]=="Male")&(result["Category"]=="Electronics")]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
0,1001,201,Laptop,Electronics,1,65000,Kochi,Completed,65000,Akhil,24,Male,Gold,Kochi
6,1007,207,Mouse,Electronics,4,900,Thrissur,Completed,3600,Arjun,23,Male,Bronze,Thrissur
8,1009,209,Webcam,Electronics,2,3200,Kochi,Completed,6400,Nikhil,28,Male,Gold,Kochi
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,Sreehari,25,Male,Silver,Kollam
12,1013,213,Printer,Electronics,1,18500,Kochi,Completed,18500,Joel,29,Male,Gold,Kochi

In [92]:
# 41. Find Silver members whose Quantity is greater than 1.
result[(result["Membership"]=="Silver")&(result["Quantity"]>1)]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
1,1002,202,Headphones,Electronics,2,2500,Thrissur,Completed,5000,Anjali,27,Female,Silver,Thrissur
10,1011,211,USB Hub,Electronics,3,1100,Kollam,Completed,3300,Sreehari,25,Male,Silver,Kollam

In [93]:
# 42. Find customers from Thrissur whose orders have TotalAmount greater than 5000.
result[(result["City_x"] == "Thrissur") & (result["TotalAmount"] > 5000)]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
14,1015,215,Microphone,Electronics,2,4500,Thrissur,Completed,9000,Keerthana,27,Female,Gold,Thrissur

In [ ]:
# 43. Find Gold members whose total spending is greater than 15000 using groupby() and a condition.
gold_spending = result[result["Membership"] == "Gold"].groupby("CustomerName")["TotalAmount"].sum()
gold_spending[gold_spending > 15000]

CustomerName
Akhil    65000
Joel     18500
Sneha    29000
Name: TotalAmount, dtype: int64

In [95]:
# 44. Find the total revenue of Completed orders for each Membership type.
result[result["Status"] == "Completed"].groupby("Membership")["TotalAmount"].sum()

Membership
Bronze      3600
Gold      142800
Silver      8300
Name: TotalAmount, dtype: int64

In [96]:
# 45. Find the total revenue generated by each City for Gold members only.
result[result["Membership"] == "Gold"].groupby("City_x")["TotalAmount"].sum()

City_x
Kochi       95300
Kollam      29000
Kottayam     9500
Thrissur     9000
Name: TotalAmount, dtype: int64

In [97]:
# 46. Find the average TotalAmount for Male and Female customers separately.
result.groupby("Gender")["TotalAmount"].mean()

Gender
Female     9728.571429
Male      18162.500000
Name: TotalAmount, dtype: float64

In [102]:
# 47. Find customers who have at least one Cancelled order.
result[result["Status"] == "Cancelled"]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
4,1005,205,Desk,Furniture,1,12000,Trivandrum,Cancelled,12000,Vishnu,35,Male,Silver,Trivandrum
13,1014,214,Sofa,Furniture,1,28000,Kottayam,Cancelled,28000,Gokul,36,Male,Silver,Kottayam

In [99]:
# 48. Find customers who purchased Furniture and have Gold membership.
result[(result["Category"] == "Furniture") & (result["Membership"] == "Gold")]

,OrderID,CustomerID,Product,Category,Quantity,UnitPrice,City_x,Status,TotalAmount,CustomerName,Age,Gender,Membership,City_y
9,1010,210,Study Table,Furniture,1,9500,Kottayam,Completed,9500,Athira,30,Female,Gold,Kottayam

In [ ]:
# 49. Find the top 3 customers based on total Completed-order revenue.
completed = result[result["Status"] == "Completed"]
completed.groupby("CustomerName")["TotalAmount"].sum().sort_values(ascending=False).head(3)

In [103]:
# 50. Create a final customer summary containing CustomerName, Membership, City, number of orders, total
# quantity purchased, and total revenue.
summary = result.groupby(["CustomerName", "Membership", "City_x"]).agg(
    NumberOfOrders=("OrderID", "count"),
    TotalQuantity=("Quantity", "sum"),
    TotalRevenue=("TotalAmount", "sum")
)

summary

,,,NumberOfOrders,TotalQuantity,TotalRevenue
CustomerName,Membership,City_x,,,
Akhil,Gold,Kochi,1,1,65000
Anjali,Silver,Thrissur,1,2,5000
Arjun,Bronze,Thrissur,1,4,3600
Athira,Gold,Kottayam,1,1,9500
Devika,Silver,Kozhikode,1,1,7000
Fathima,Bronze,Trivandrum,1,2,3200
Gokul,Silver,Kottayam,1,1,28000
Joel,Gold,Kochi,1,1,18500
Keerthana,Gold,Thrissur,1,2,9000
Meera,Gold,Kochi,1,3,5400
Nikhil,Gold,Kochi,1,2,6400
Rahul,Bronze,Kozhikode,1,1,8500
Sneha,Gold,Kollam,1,2,29000
Sreehari,Silver,Kollam,1,3,3300
Vishnu,Silver,Trivandrum,1,1,12000