In [42]:
import pandas as pd

In [43]:
loan=pd.read_csv("loan_approval.csv")
df=pd.DataFrame(loan)
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [44]:
df.shape

(2000, 8)

In [45]:
df.columns

Index(['name', 'city', 'income', 'credit_score', 'loan_amount',
       'years_employed', 'points', 'loan_approved'],
      dtype='object')

In [46]:
df.describe()

              income  credit_score   loan_amount  years_employed       points
count    2000.000000   2000.000000   2000.000000     2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000       20.441000    56.680000
std     34487.874907    160.564945  14207.320147       11.777813    18.638033
min     30053.000000    300.000000   1022.000000        0.000000    10.000000
25%     61296.250000    433.000000  12748.750000       10.000000    45.000000
50%     90387.500000    576.000000  25661.500000       21.000000    55.000000
75%    120099.750000    715.000000  37380.500000       31.000000    70.000000
max    149964.000000    850.000000  49999.000000       40.000000   100.000000

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2000 non-null   object
 1   city            2000 non-null   object
 2   income          2000 non-null   int64
 3   credit_score    2000 non-null   int64
 4   loan_amount     2000 non-null   int64
 5   years_employed  2000 non-null   int64
 6   points          2000 non-null   float64
 7   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4), object(2)
memory usage: 111.5+ KB

In [48]:
df.dtypes

name               object
city               object
income              int64
credit_score        int64
loan_amount         int64
years_employed      int64
points            float64
loan_approved        bool
dtype: object

In [49]:
df=df.drop(["name","city"],axis=1)

In [50]:
df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [51]:
X=df.drop("loan_approved",axis=1)
y=df["loan_approved"]

In [52]:
X

      income  credit_score  loan_amount  years_employed  points
0     113810           389        39698              27    50.0
1      44592           729        15446              28    55.0
2      33278           584        11189              13    45.0
3     127196           344        48823              29    50.0
4      66048           496        47174               4    25.0
...      ...           ...          ...             ...     ...
1995   92163           770        12251              13    85.0
1996   38799           635        48259              17    40.0
1997   41957           763        16752               5    60.0
1998  139022           360        24031              35    55.0
1999   41188           482        31397               6    20.0

[2000 rows x 5 columns]

In [53]:
y

0       False
1       False
2       False
3       False
4       False
        ...
1995     True
1996    False
1997     True
1998    False
1999    False
Name: loan_approved, Length: 2000, dtype: bool

In [54]:
df.isna().sum()

income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [55]:
X.dtypes

income              int64
credit_score        int64
loan_amount         int64
years_employed      int64
points            float64
dtype: object

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [60]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [61]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9733333333333334