In [1]:
import pandas as pd

In [5]:
custom=pd.read_csv("/Users/noufa/Desktop/eda_practice/sample/custom_windows (1).csv")
c_df=pd.DataFrame(custom)
c_df

   id      name  age   location  salary
0   1      Ross   32  Ahmedabad    2000
1   2    Rachel   25      Delhi    1500
2   3  Chandler   23       Kota    2000
3   4    Monika   25     Mumbai    6500
4   5      Mike   27     Bhopal    8500
5   6    Phoebe   22         MP    4500
6   7      Joey   24     Indore   10000

In [6]:
order=pd.read_csv("/Users/noufa/Desktop/eda_practice/sample/order_windows (1).csv")
o_df=pd.DataFrame(order)
o_df

   oid               dat  id  amount
0  102  08-10-2016 00:00   3    3000
1  100  08-10-2016 00:00   3    1500
2  101  20-11-2016 00:00   2    1560
3  103  20-05-2015 00:00   4    2060

In [ ]:
result=pd.merge(c_df,o_df,on="id",how="inner").sort_values(by="amount",ascending=False)
result

   id      name  age location  salary  oid               dat  amount
1   3  Chandler   23     Kota    2000  102  08-10-2016 00:00    3000
3   4    Monika   25   Mumbai    6500  103  20-05-2015 00:00    2060
0   2    Rachel   25    Delhi    1500  101  20-11-2016 00:00    1560
2   3  Chandler   23     Kota    2000  100  08-10-2016 00:00    1500

In [8]:
result1=pd.merge(c_df,o_df,on="id",how="left")
result1

   id      name  age   location  salary    oid               dat  amount
0   1      Ross   32  Ahmedabad    2000    NaN               NaN     NaN
1   2    Rachel   25      Delhi    1500  101.0  20-11-2016 00:00  1560.0
2   3  Chandler   23       Kota    2000  102.0  08-10-2016 00:00  3000.0
3   3  Chandler   23       Kota    2000  100.0  08-10-2016 00:00  1500.0
4   4    Monika   25     Mumbai    6500  103.0  20-05-2015 00:00  2060.0
5   5      Mike   27     Bhopal    8500    NaN               NaN     NaN
6   6    Phoebe   22         MP    4500    NaN               NaN     NaN
7   7      Joey   24     Indore   10000    NaN               NaN     NaN

In [9]:
result2=pd.merge(c_df,o_df,on="id",how="right")
result2

   id      name  age location  salary  oid               dat  amount
0   3  Chandler   23     Kota    2000  102  08-10-2016 00:00    3000
1   3  Chandler   23     Kota    2000  100  08-10-2016 00:00    1500
2   2    Rachel   25    Delhi    1500  101  20-11-2016 00:00    1560
3   4    Monika   25   Mumbai    6500  103  20-05-2015 00:00    2060

In [11]:
result3=pd.merge(c_df,o_df,on="id",how="outer")
result3

   id      name  age   location  salary    oid               dat  amount
0   1      Ross   32  Ahmedabad    2000    NaN               NaN     NaN
1   2    Rachel   25      Delhi    1500  101.0  20-11-2016 00:00  1560.0
2   3  Chandler   23       Kota    2000  102.0  08-10-2016 00:00  3000.0
3   3  Chandler   23       Kota    2000  100.0  08-10-2016 00:00  1500.0
4   4    Monika   25     Mumbai    6500  103.0  20-05-2015 00:00  2060.0
5   5      Mike   27     Bhopal    8500    NaN               NaN     NaN
6   6    Phoebe   22         MP    4500    NaN               NaN     NaN
7   7      Joey   24     Indore   10000    NaN               NaN     NaN

In [ ]:
result4=pd.merge(c_df,o_df,on="id",how="inner").sort_values(by="salary")
result4

   id      name  age location  salary  oid               dat  amount
0   2    Rachel   25    Delhi    1500  101  20-11-2016 00:00    1560
1   3  Chandler   23     Kota    2000  102  08-10-2016 00:00    3000
2   3  Chandler   23     Kota    2000  100  08-10-2016 00:00    1500
3   4    Monika   25   Mumbai    6500  103  20-05-2015 00:00    2060

In [20]:
result=pd.merge(c_df,o_df,on="id",how="inner")
result.loc[result["salary"]>2000]

   id    name  age location  salary  oid               dat  amount
3   4  Monika   25   Mumbai    6500  103  20-05-2015 00:00    2060

In [34]:
pd.merge(c_df, o_df, on="id", how="inner")["salary"] > 2000
pd.merge(c_df, o_df, on="id", how="inner").query("salary > 2000")

   id    name  age location  salary  oid               dat  amount
3   4  Monika   25   Mumbai    6500  103  20-05-2015 00:00    2060